### ISSUE TITLE
Bad LL 3D Data Even Though Targets Are Seen

### ISSUE THREAD

**Issue by vyang2968** [LimelightVision/limelightlib-wpijava#13]
Using `LimelightHelpers.getBotPose3d("")` works amazingly and returns exactly what I need. However, out of curiosity, I tried `LimelightHelpers.getBotPose3d_wpiBlue("")` and the one for the red, and it prints `Bad Limelight 3D Data` on the RioLog. I am not sure why it works for one and not for the other. Also what is the difference?

**Comment by bhjelstrom** [comment]
It's great to hear that botpose is working well for you. Are you using the latest image (2023.2)? https://docs.limelightvision.io/en/latest/software_change_log.html#id1
2023.2 is required for wpired and wpiblue to work.

WPIRed and WPIBlue simply use different the coordinate systems that match the following: 
![image](https://user-images.githubusercontent.com/13728935/218019913-49ce55e0-976f-4fb8-832e-4d3dbd5fd8d7.png)

If you're a blue driver, wpiBlue puts the origin at the rightmost side of your driverstation wall.
If you're a red driver, wpiRed puts the origin at the rightmost side of your driverstation wall.

**Comment by vyang2968** [comment]
updating the limelight to the latest version worked. thanks for the help!
