### ISSUE TITLE
Set Limelight Camera Pose Feature Request

### ISSUE THREAD

**Issue by vyang2968** [LimelightVision/limelightlib-wpijava#16]
I'm not sure where to post feature requests, so forgive me if this is the wrong space. Anyways, it would be useful to be able to config the Limelight Camera Position using LimelightHelpers.

**Comment by bhjelstrom** [comment]
It's in V1.2!
setCameraPose_RobotSpace(String limelightName, double forward, double side, double up, double roll, double pitch, double yaw

https://github.com/LimelightVision/limelightlib-wpijava/blob/main/LimelightHelpers.java#L699

Better docs coming soon

**Comment by vyang2968** [comment]
thanks!
