### ISSUE TITLE
Neural Class ID Returns 0 for Both Game Pieces

### ISSUE THREAD

**Issue by icemannie** [LimelightVision/limelightlib-wpijava#19]
'tclass" returns a String with the game piece name while getNeuralClassID looks to return a double

Add new method to return String "name" or do something like

 public static double getNeuralClassID(String limelightName) {

        String temp = getLimelightNTString(limelightName, "tclass");

        double val = 911;
        switch (temp) {

            case "cube":
                val = 1;
                break;
            case "cone":
                val = 0;
                break;
            default:
                val = 911;
        }
        return val;

    }

**Comment by bhjelstrom** [comment]
Fixed in 1.3.1, thanks @icemannie !
