### ISSUE TITLE
2023 Field Non-Standard Mirroring

### ISSUE THREAD

**Issue by vyang2968** [LimelightVision/limelightlib-wpijava#20]
Does Limelight automatically correct for this year's non-standard field mirroring with the `getBotPose_wpiBlue` and `getBotPose_wpiRed`? If not, is Limelight planning to adjust for it or is that for the users to do?

**Comment by bhjelstrom** [comment]
WPIBlue uses a blue-alliance origin, and WPIRed uses a red-alliance origin (valid for 2023). With the community moving to blue-corner-always in 2024, we now recommend using wpiblue for just about everything moving forward
