### ISSUE TITLE
Calculate timestamp for use with WPILib pose estimators

### ISSUE THREAD

**Issue by agasser** [LimelightVision/limelightlib-wpijava#21]
The methods `getBotPose2d_wpiBlue()` and `getBotPose2d_wpiRed()` don't expose the NT entry's last change time, nor the pipeline latency. It would be really handy to have a method to call that would return an object with a `Pose2d` and a timestamp that can be plugged right into a WPILib pose estimator.

**Comment by bhjelstrom** [comment]
Fixed by none other than @agasser in 1.3
