### ISSUE TITLE
bug: crashes 2024 wpilib roboRio

### ISSUE THREAD

**Issue by taciturnaxolotl** [LimelightVision/limelightlib-wpijava#23]
When getting botpose3d in wpilib 2024 it starts a crash loop on the RoboRio

**Comment by yabberyabber** [comment]
Could you share the stacktrace, the log, or potentially even some of your code? It would be useful for the maintainers to be able to see how/when it crashes

**Comment by taciturnaxolotl** [comment]
I can share code but I don't have the stack trace rigjt now (currently at comps) df1317/2024-crescendo

**Comment by taciturnaxolotl** [comment]
https://github.com/df1317/2024-crescendo/commit/aebb88070ed846ced06940d51d295d86a73a5485 her is the latest code with limelight helper. Because of the issues we ended up just switching to bare network tables one commit later.

**Comment by bhjelstrom** [comment]
We haven't had any other reports of this and were not able to reproduce. I think we will close for now given all of the updates that have happened since February, but feel free to open again if you experience the issue.
