### ISSUE TITLE
Two possible java helper bugs -- getRawFiducials() and getRawDetections()...

### ISSUE THREAD

**Issue by rtestardi** [LimelightVision/limelightlib-wpijava#32]
1. should getRawFiducials() be public instead of private, to match getRawDetections()?
2. should getRawDetections:valsPerEntry be 12 instead of 11, since we index from 0 to 11 from the doubles array?
3. When we make these changes, everything works as expected, allowing us to manually pick fiducials or detections from those that are visible.
Thanks!

**Comment by bhjelstrom** [comment]
Fixed, thanks!
