### ISSUE TITLE
JSON POJO still not public

### ISSUE THREAD

**Issue by agasser** [LimelightVision/limelightlib-wpijava#9]
JSON data still cannot be used outside of `frc.robot`. `LimelightHelpers.LimelightResults` is still package private.

https://github.com/LimelightVision/limelightlib-wpijava/blob/812c9130d403ef7c86f4253efa94ab4bbce09a8e/LimelightHelpers.java#L355

**Comment by bhjelstrom** [comment]
noooooo

**Comment by bhjelstrom** [comment]
fixed
